rootUrl: http://localhost:8080
windowSize: 800x600
browsers:
  PhantomJS:
    screenshotMode: fullpage
    desiredCapabilities:
      browserName: phantomjs

system:
  plugins:
    gemini-optipng: true
