language: node_js
node_js:
  - "8"
  - "10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  - yarn build

after_script: greenkeeper-lockfile-upload

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: ${FIREBASE_API_TOKEN}
  on:
    branch: master
