language: node_js
node_js:
  - "6"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - yarn global add greenkeeper-lockfile@1 gemini

before_script:
  - greenkeeper-lockfile-update
  - phantomjs --webdriver=4444 &

script:
  - yarn build
  - yarn start &
  - yarn test-ci

after_script: greenkeeper-lockfile-upload

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: ${FIREBASE_API_TOKEN}
  on:
    branch: master
