language: node_js
node_js:
  - "6"

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  # Ensure we rebuild all packages, specifically binaries
  - yarn install --force

script:
  - yarn build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: ${FIREBASE_API_TOKEN}
  on:
    branch: master
