language: node_js
node_js:
  - "6"

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn global add firebase-tools

  # TODO: work out if this is needed, and remove it
  - cd node_modules/phantomjs-prebuilt
  - node install.js

script:
  - yarn run build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
