language: node_js
node_js:
  - "6"

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  # Ensure we rebuild all packages, specifically binaries
  - yarn install --force
  - yarn global add firebase-tools

script:
  - yarn build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
