nodeLinker: node-modules

packageExtensions:
  "@webpack-cli/package-utils@*":
    dependencies:
      cross-spawn: 7.0.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
