pool:
  vmImage: "ubuntu-16.04"

trigger:
- master

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn'
  inputs:
    Arguments: 'upgrade-yarn'
  env:
    YARN_IGNORE_PATH: 1

- task: CacheBeta@0
  inputs:
    key: yarn | $(Agent.OS) | yarn.lock
    path: $(YARN_CACHE_FOLDER)
  displayName: Cache Yarn packages

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn'
  inputs:
    Arguments: '--frozen-lockfile'

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Run e2e tests'
  inputs:
    Arguments: 'test:e2e:ci'
  env:
    CYPRESS_RECORD_KEY: $(CYPRESS_RECORD_KEY)

