pool:
  name: Hosted Ubuntu 1604
  demands: yarn

steps:
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Yarn'

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  displayName: 'Run e2e tests'
  inputs:
    Arguments: 'test:e2e:ci'
  env:
    CYPRESS_RECORD_KEY: $(CYPRESS_RECORD_KEY)

